### ISSUE TITLE
Non-model references?

### ISSUE THREAD

**Issue by chicopollo** [KCCG/mity#54]
Hi, I am very interested in applying the mity pipeline to non-model organisms for which there are annotated mitochondrial genomes. Is it possible to pass an argument to mity providing my own reference files? 

It would be greatly appreciated

**Comment by drmjc** [comment]
Hi, mity has the functionality to support different references, but not to provide a custom one. if you know python it would be pretty easy to add a new one and to put the custom fasta file in the right location. However, because mity adds lots of human annotations, I think you'd be better off running freebayes using the sensitive parameters that are coded into the app.
